//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2025 LiangNing7 <liangning2277@gmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/LiangNing7/minerx.

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	provision "github.com/LiangNing7/kube-demo/pkg/apis/provision"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ProvisionRequest)(nil), (*provision.ProvisionRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionRequest_To_provision_ProvisionRequest(a.(*ProvisionRequest), b.(*provision.ProvisionRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*provision.ProvisionRequest)(nil), (*ProvisionRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_provision_ProvisionRequest_To_v1alpha1_ProvisionRequest(a.(*provision.ProvisionRequest), b.(*ProvisionRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProvisionRequestList)(nil), (*provision.ProvisionRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionRequestList_To_provision_ProvisionRequestList(a.(*ProvisionRequestList), b.(*provision.ProvisionRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*provision.ProvisionRequestList)(nil), (*ProvisionRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_provision_ProvisionRequestList_To_v1alpha1_ProvisionRequestList(a.(*provision.ProvisionRequestList), b.(*ProvisionRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProvisionRequestSpec)(nil), (*provision.ProvisionRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionRequestSpec_To_provision_ProvisionRequestSpec(a.(*ProvisionRequestSpec), b.(*provision.ProvisionRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*provision.ProvisionRequestSpec)(nil), (*ProvisionRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_provision_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(a.(*provision.ProvisionRequestSpec), b.(*ProvisionRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProvisionRequestStatus)(nil), (*provision.ProvisionRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionRequestStatus_To_provision_ProvisionRequestStatus(a.(*ProvisionRequestStatus), b.(*provision.ProvisionRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*provision.ProvisionRequestStatus)(nil), (*ProvisionRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_provision_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(a.(*provision.ProvisionRequestStatus), b.(*ProvisionRequestStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ProvisionRequest_To_provision_ProvisionRequest(in *ProvisionRequest, out *provision.ProvisionRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProvisionRequestSpec_To_provision_ProvisionRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProvisionRequestStatus_To_provision_ProvisionRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProvisionRequest_To_provision_ProvisionRequest is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionRequest_To_provision_ProvisionRequest(in *ProvisionRequest, out *provision.ProvisionRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionRequest_To_provision_ProvisionRequest(in, out, s)
}

func autoConvert_provision_ProvisionRequest_To_v1alpha1_ProvisionRequest(in *provision.ProvisionRequest, out *ProvisionRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_provision_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_provision_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_provision_ProvisionRequest_To_v1alpha1_ProvisionRequest is an autogenerated conversion function.
func Convert_provision_ProvisionRequest_To_v1alpha1_ProvisionRequest(in *provision.ProvisionRequest, out *ProvisionRequest, s conversion.Scope) error {
	return autoConvert_provision_ProvisionRequest_To_v1alpha1_ProvisionRequest(in, out, s)
}

func autoConvert_v1alpha1_ProvisionRequestList_To_provision_ProvisionRequestList(in *ProvisionRequestList, out *provision.ProvisionRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]provision.ProvisionRequest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ProvisionRequestList_To_provision_ProvisionRequestList is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionRequestList_To_provision_ProvisionRequestList(in *ProvisionRequestList, out *provision.ProvisionRequestList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionRequestList_To_provision_ProvisionRequestList(in, out, s)
}

func autoConvert_provision_ProvisionRequestList_To_v1alpha1_ProvisionRequestList(in *provision.ProvisionRequestList, out *ProvisionRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ProvisionRequest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_provision_ProvisionRequestList_To_v1alpha1_ProvisionRequestList is an autogenerated conversion function.
func Convert_provision_ProvisionRequestList_To_v1alpha1_ProvisionRequestList(in *provision.ProvisionRequestList, out *ProvisionRequestList, s conversion.Scope) error {
	return autoConvert_provision_ProvisionRequestList_To_v1alpha1_ProvisionRequestList(in, out, s)
}

func autoConvert_v1alpha1_ProvisionRequestSpec_To_provision_ProvisionRequestSpec(in *ProvisionRequestSpec, out *provision.ProvisionRequestSpec, s conversion.Scope) error {
	out.IngressEntrance = in.IngressEntrance
	out.BusinessDbVolume = provision.DbVolume(in.BusinessDbVolume)
	out.NamespaceName = in.NamespaceName
	return nil
}

// Convert_v1alpha1_ProvisionRequestSpec_To_provision_ProvisionRequestSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionRequestSpec_To_provision_ProvisionRequestSpec(in *ProvisionRequestSpec, out *provision.ProvisionRequestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionRequestSpec_To_provision_ProvisionRequestSpec(in, out, s)
}

func autoConvert_provision_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(in *provision.ProvisionRequestSpec, out *ProvisionRequestSpec, s conversion.Scope) error {
	out.IngressEntrance = in.IngressEntrance
	out.BusinessDbVolume = DbVolume(in.BusinessDbVolume)
	out.NamespaceName = in.NamespaceName
	return nil
}

// Convert_provision_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec is an autogenerated conversion function.
func Convert_provision_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(in *provision.ProvisionRequestSpec, out *ProvisionRequestSpec, s conversion.Scope) error {
	return autoConvert_provision_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(in, out, s)
}

func autoConvert_v1alpha1_ProvisionRequestStatus_To_provision_ProvisionRequestStatus(in *ProvisionRequestStatus, out *provision.ProvisionRequestStatus, s conversion.Scope) error {
	out.IngressReady = in.IngressReady
	out.DbReady = in.DbReady
	return nil
}

// Convert_v1alpha1_ProvisionRequestStatus_To_provision_ProvisionRequestStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionRequestStatus_To_provision_ProvisionRequestStatus(in *ProvisionRequestStatus, out *provision.ProvisionRequestStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionRequestStatus_To_provision_ProvisionRequestStatus(in, out, s)
}

func autoConvert_provision_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(in *provision.ProvisionRequestStatus, out *ProvisionRequestStatus, s conversion.Scope) error {
	out.IngressReady = in.IngressReady
	out.DbReady = in.DbReady
	return nil
}

// Convert_provision_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus is an autogenerated conversion function.
func Convert_provision_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(in *provision.ProvisionRequestStatus, out *ProvisionRequestStatus, s conversion.Scope) error {
	return autoConvert_provision_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(in, out, s)
}
